openapi: 3.0.0
info:
  title: アンケート
  version: '1.0'
  description: アンケート
  contact:
    name: FCApp
servers:
  - url: 'http://localhost:3000/api'
    description: Test server
paths:
  /survey:
    get:
      summary: アンケートURLリスト
      tags:
        - Survey
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  client_survey_list:
                    type: array
                    description: 顧客アンケートリスト
                    items:
                      $ref: '#/components/schemas/survey'
                  staff_survey_list:
                    type: array
                    description: スタッフアンケートリスト
                    items:
                      $ref: '#/components/schemas/survey'
                  status:
                    type: string
                required:
                  - status
              examples:
                example-1:
                  value:
                    client_survey_list:
                      - url: 'http://localhost:8080/api/survey/1'
                        name: ファイナンスセミナー
                        event_date: '2019-11-01'
                        start_time: '09:00'
                        end_time: '12:00'
                        category: 午前
                      - url: 'http://localhost:8080/api/survey/20'
                        name: 相談会
                        event_date: '2019-11-01'
                        start_time: '09:00'
                        end_time: '12:00'
                        category: ''
                    staff_survey_list:
                      - url: 'http://localhost:8080/api/staff_survey/10'
                        name: スタッフ用アンケート
                        event_date: ''
                        start_time: ''
                        end_time: ''
                        category: ''
                    status: success
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  error:
                    type: string
                required:
                  - status
                  - error
      description: アンケートURLリスト取得
      parameters:
        - schema: {}
          in: header
          name: Authorization
          description: 'Bearer {$token}'
          required: true
      operationId: getSurveyList
components:
  schemas:
    survey:
      title: 顧客アンケート
      type: object
      description: 顧客アンケートモデル
      properties:
        url:
          type: string
          description: アンケートURL
        name:
          type: string
          description: 講義・イベント名
        event_date:
          type: string
          description: 開催日
        start_time:
          type: string
          description: 開始時刻
        end_time:
          type: string
          description: 終了時刻
        category:
          type: string
          description: 講義カテゴリー
      required:
        - url
  securitySchemes:
    Authorization:
      type: http
      scheme: Bearer
      description: JWT
