openapi: 3.0.0
info:
  title: アンケート
  version: '1.0'
  description: アンケート
  contact:
    name: FCApp
servers:
  - url: 'http://localhost:3000/api'
    description: Test server
paths:
  /survey:
    get:
      summary: アンケートURLリスト
      tags:
        - Survey
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  survey_url_list:
                    type: array
                    items:
                      type: string
                  status:
                    type: string
                required:
                  - survey_url_list
              examples:
                example-1:
                  value:
                    survey_url_list:
                      - 'http://localhost:8080/api/survey/1'
                      - 'http://localhost:8080/api/survey/2'
                    status: success
                example-2:
                  value:
                    survey_url_list:
                      - 'http://localhost:8080/api/survey/1'
                      - 'http://localhost:8080/api/staff_survey/20'
                    status: success
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  error:
                    type: string
                required:
                  - status
                  - error
      description: アンケートURLリスト取得
      parameters:
        - schema: {}
          in: header
          name: Authorization
          description: 'Bearer {$token}'
          required: true
      operationId: getSurveyList
components:
  schemas: {}
  securitySchemes:
    Authorization:
      type: http
      scheme: Bearer
      description: JWT
